# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 23 Jul 2009 15:38:16 +0200
*	@ALL	1
*	@admin	16
contact_us	@user	1
womoz	@user	1
*	@user	2
