<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: julia
 * Date: Thu, 11 Feb 2010 16:37:08 +0100
 */

$conf['title'] = 'Women &amp; Mozilla';
$conf['start'] = 'womoz';
$conf['template'] = 'mozillacommunity';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['recent_days'] = 30;
$conf['tpl']['artic']['left_sidebar_content'] = 'main';
$conf['tpl']['artic']['right_sidebar_content'] = 'main,user,group,namespace';
// end auto-generated content
